name: Comment Responder
on:
  issue_comment:
    types: [created]

jobs:
  mentioned:
    runs-on: ubuntu-latest
    if: github.event.comment.body == '@JuliaControlBot test-plots'
    steps:
      - id: get_user_permissons
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/collaborators/:user/permission
          repository: ${{ github.repository }}
          user: ${{ github.event.comment.user.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: parse_permisson
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.get_user_permissons.outputs.data }}
          permission: "permission"


      - name: Is admin
        if: steps.parse_permisson.outputs.permission == 'admin'
        run: |
          echo Is admin

      - name: Is PR
        if: github.event.issue.pull_request != null
        run: |
          echo Is PR
          
      - name: Is request
        if: github.event.comment.body == '@JuliaControlBot test-plots' 
        run: |
          echo Is PR

      - name: PR ping ControlExamplePlots
        if: github.event.issue.pull_request != null && steps.parse_permisson.outputs.permission == 'admin' && false
        run: |
          curl -X POST https://api.github.com/repos/mfalt/ControlExamplePlots.jl/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN_BOT }} \
          --data '{"event_type": "prupdate", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "pr_number":  ${{ github.event.issue.number }} }}'
