name: Remote Dispatch Action Initiator

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PR ping ControlExamplePlots
        if: ${{ secrets.ACCESS_TOKEN_BOT }} != null # To make sure that the script wont fail when on a fork
        run: |
          curl -X POST https://api.github.com/repos/mfalt/ControlExamplePlots.jl/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN_BOT }} \
          --data '{"event_type": "prupdate", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "pr_number":  ${{ github.event.number }} }}'
